### ISSUE TITLE
I want to collaboration with you.

### ISSUE THREAD

**Issue by TiNredmc** [ksbcboy/Arduino-U2F#2]
Hello. I'm working on the port of the TeensyU2F. From the teensyLC to teensy++ 2.0 (clone).
Can you help me do this ? I would share the roughly modified code.

**Comment by ksbcboy** [comment]
Sorry, I'm busy for my other project, but I can upload my Arduino U2F code for you, I think that will help you!

**Comment by TiNredmc** [comment]
Oh. Thnaks. Mine is here (github.com/TiNredmc/AVRu2f)

**Comment by TiNredmc** [comment]
Hi. Can I have the code ?
